project:
  type: website

website:
  navbar:
    foreground: light
    left:
      - href: index.qmd
        text: About Tegveer  
      - href: Introduction.qmd
        text: Introduction
      - href: Data-Sources.qmd
        text: Data Sources
      - href: Data-Visualization.qmd
        text: Data Visualization
      - href: Exploratory-Data-Analysis.qmd
        text: Exploratory Data Analysis
      - href: ARMA-ARIMA-SARIMA.qmd
        text: ARMA/ARIMA/SARIMA Models
      - href: ARIMAX-SARIMAX-VAR.qmd
        text: ARIMAX/SARIMAX/VAR Models 
      - href: Financial-Models.qmd
        text: Financial Time Series Models
      - href: Deep-Learning.qmd
        text: Deep Learning for TS
      - href: Conclusion.qmd
        text: Conclusion
    pinned: true
    collapse: true

format:
  html:
    theme: 
      - lux
      - custom.scss
    to: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    code: true

editor: visual
